# Site settings
title: Caio Delgado 
description: Used to be SysAdmin, now SRE
baseurl: "" 
url: "https://caiodelgado.dev" # the base hostname & protocol for your site
twitter_username: caiodelgadonew
github_username:  caiodelgadonew

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

